### ISSUE TITLE
Unable to add custome Image

### ISSUE THREAD

**Issue by jvd001** [0011ai/deailab#12]
By adding the image ubuntu:latest I got the message 

3:24:55 PM
Adding ubuntu:latest image

**3:24:55 PM
Failed to add Image ubuntu:latest: list index out of range**

What is going wrong or what do I need to do to add Custome Images

TX, Jaco

**Comment by trungleduc** [comment]
Hi, do you have the ifps desktop app running?

**Comment by JvD007** [comment]
No, I'm running ipfs and bacalhau as a daemon and running it in a private setup on Linux servers

**Comment by jvd001** [comment]
We have installed everything on a clean server, with IPFS Desktop 0.31 and running. but, we have still  the same problem.

What can be the problem?  Are the log files we can check etc

**Comment by 0011ai** [comment]
Are you able to run a simple hello world python code with the normal python docker image?

**Comment by JvD007** [comment]
Yes, that works fine. It's only adding custom image

I'm running this in Jupyter and works also fine

import pprint

from bacalhau_sdk.api import submit
from bacalhau_sdk.config import get_client_id
from bacalhau_apiclient.models.storage_spec import StorageSpec
from bacalhau_apiclient.models.spec import Spec
from bacalhau_apiclient.models.job_spec_language import JobSpecLanguage
from bacalhau_apiclient.models.job_spec_docker import JobSpecDocker
from bacalhau_apiclient.models.publisher_spec import PublisherSpec
from bacalhau_apiclient.models.deal import Deal


data = dict(
    APIVersion='V1beta1',
    ClientID=get_client_id(),
    Spec=Spec(
        engine="Docker",
        publisher_spec=PublisherSpec(type="IPFS"),
        docker=JobSpecDocker(
            image="ubuntu:18.04",
            entrypoint=["echo", "Hello World new Ubuntu image!"],
        ),
        language=JobSpecLanguage(job_context=None),
        wasm=None,
        resources=None,
        timeout=1800,
        outputs=[
            StorageSpec(
                storage_source="IPFS",
                name="outputs",
                path="/outputs",
            )
        ],
        deal=Deal(concurrency=1),
        do_not_track=False,
    ),
)

________________________________

**Comment by 0011ai** [comment]
I can reproduce it. Will check what is wrong.

**Comment by 0011ai** [comment]
There were two issues. 
One: Ubuntu:latest does not have python3 installed so we cannot use it. I added a check that throws an error if this happens so you know why the image cannot be added.
Two: 
There was another bug due to bacalhau introducing a new state "New" before "InProgress" which deairequest was not checking for. You need to use version 0.0.19 of deairequest. V0.1.11 of deailab should have reference the new version of deairequest.

**Comment by 0011ai** [comment]
Hopefully this clarifies things.
